config/routes.rb
Rails.application.routes.draw do
  root 'quotes#index'
  resources :quotes
  get 'about', to: 'quotes#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote < ApplicationRecord
	validates :saying, presence: true, length: { maxium: 140, minimum: 3 }
	validates :movie_reference, presence: true, length: { maximum: 100, minimum: 3 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
	def index
		@quote = Quote.order("RANDOM()").first
	end

	def create
		@quote = Quote.create(quote_params)

		if @quote.invalid?
			flash[:error] = "<strong class='bold brand-color h3'>SORRY!</strong> The data you entered is invalid and could not be saved."
		end

		redirect_to root_path
	end

	def about
		
	end

	private

	def quote_params
		params.require(:quote).permit(:saying, :movie_reference)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Splurty</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header class='d-flex align-items-center justify-content-around px-sm-5'>

        <%= link_to 'SPLURTY', root_path, :class => 'bold brand-color h4 mb-0', :id => 'logo' %>

        <h1 class='h6 hidden-md-down mr-auto ml-5 serif italic mb-0'> - Splurting out Arnold Schwarzenneger movie quotes for fun!</h1>

        <nav>
          <%= link_to 'Contribute', new_quote_path, :class => 'bold px-1 pb-1 mr-2 mr-sm-4', data: { toggle: 'modal', target: '#newQuoteModal' } %>
          <%= link_to 'About Us', about_path, :class => 'bold px-1 pb-1 ml-2 ml-sm-4' %>
        </nav>
    </header>

    <div class="modal fade" id="newQuoteModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
            <h4 class="pl-4 h5 modal-title" id="myModalLabel">Contribute your favourite Arnie movie quote!</h4>
          </div>
          <%= simple_form_for Quote.new do |f| %>
            <div class="modal-body">
                <%= f.input :saying, label: 'What is your favourite Arnie movie Quote?', placeholder: 'Your clothes, give them to me, now!' %>
                <%= f.input :movie_reference, label: 'What movie is it from?', placeholder: 'Terminator' %>
            </div>
            <div class="modal-footer">
              <%= f.submit :'Create', class: 'btn btn-brand' %>
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <main class='d-flex flex-column align-items-center px-5 mt-4'>
      <% if flash[:error].present? %>
        <%= flash[:error].html_safe %>
      <% end %>

      <%= yield %>
    </main>

    <footer class='d-flex flex-column align-items-center justify-content-center py-4 px-5'>
        <%= link_to 'Show me another quote!', root_path, :class => 'btn btn-secondary btn-brand h5 mb-auto mr-md-auto bold serif italic mb-0', data: { no_turbolink: true } %>
        <p class='mt-auto ml-md-auto serif italic'>Proudly built by <a class='bold brand-color' href="https://github.com/Davey-Wright">Davey</a> in Bridgend, Wales.</p>
    </footer>

  </body>
</html>

app/views/quotes/about.html.erb
<div class='col-md-8 pt-5'>
	<h1 class='mb-3'>About Splurty</h1>
	<p class='mb-3'>
    Splurty was built by <a target="_blank" class='bold brand-color' href="https://github.com/Davey-Wright">Davey</a> in Bridgend, Wales. Splurty is an Arnold Shwarzenneger movie quotes generator. This is Daveys first Web App of many that he hopes to build while he is a student at <a href="https://thefirehoseproject.com/" class='bold brand-color'>The Firehose Project</a>.
  </p>

  <div class='my-5 row'>
    <div class=' col-md-6'>
      <%= image_tag 'pooch.png' %>
    </div>
  	<div class='col-md-6 mt-4 mt-md-0'>
  		<h2 class='h4'>Davey Wright</h2>
  		<p><a target="_blank" class='bold brand-color' href="https://github.com/Davey-Wright">Davey</a> is a Web Developer and student at <a href="https://thefirehoseproject.com/" class='bold brand-color'>The Firehose Project</a>. He likes strong coffee, kitesurfing and learning how to code while making cool things.</p>
  	</div>
  </div>

</div>

app/views/quotes/index.html.erb
<h3 class='h4 pt-5 mr-auto'>SPLURTY / No. <%= @quote.id %> - <span class='h5 italic serif text-muted'>We could all use a little more Arnie in our lives...</span></h3>

<h1 class='quote col-md-9 mt-5'><%= @quote.saying %></h1>

<div class='italic ml-auto mt-4 mb-5 d-flex flex-column'>
	<h2 class='h5'> Arnold Schwarzenneger</h2>
	<h3 class='h6 ml-md-auto'> - <%= @quote.movie_reference %></h3>
</div>